name: Ultimate Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Check and Setup Gradle Wrapper
      run: |
        if [ ! -f gradlew ] || [ ! -d gradle/wrapper ]; then
          echo "Gradle Wrapper missing. Attempting automatic setup..."
          wget https://services.gradle.org/distributions/gradle-7.0.2-bin.zip
          unzip -q gradle-7.0.2-bin.zip
          export PATH=$PWD/gradle-7.0.2/bin:$PATH
          gradle wrapper --gradle-version 7.0.2
          chmod +x ./gradlew
        else
          echo "Gradle Wrapper found."
          chmod +x ./gradlew
        fi

    - name: Cache Gradle and Android Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.kts') }}-${{ hashFiles('**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Diagnostics on Failure
      if: failure()
      run: |
        echo "Build failed. Collecting diagnostics..."
        # Example diagnostic commands:
        ./gradlew tasks --all
        # Ensure this step does not cause the workflow to fail
        true
