name: Ultimate Android CI Build with Error Handling

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Validate Gradle Wrapper
      run: |
        if [[ ! -f gradlew || ! -f gradle/wrapper/gradle-wrapper.jar ]]; then
          echo "Gradle Wrapper files are missing. Attempting to regenerate..."
          mkdir -p gradle/wrapper
          wget -O gradle/wrapper/gradle-wrapper.jar "https://github.com/gradle/gradle-wrapper/raw/master/gradle-wrapper.jar"
          echo "distributionUrl=https\://services.gradle.org/distributions/gradle-7.0.2-bin.zip" > gradle/wrapper/gradle-wrapper.properties
          echo "wrapper missing or corrupted, regenerated gradle-wrapper.jar and gradle-wrapper.properties"
        fi
        chmod +x ./gradlew

    - name: Cache Gradle and Android Dependencies
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
          ~/.android/build-cache
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}-${{ hashFiles('**/*.kts') }}-${{ hashFiles('**/gradle.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Diagnostics on Failure
      if: failure()
      run: |
        echo "Build failed. Collecting diagnostics..."
        # Example diagnostic commands:
        ./gradlew tasks --all
        # Ensure this step does not cause the workflow to fail
        true
