name: Ultimate Android CI Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2
      with:
        submodules: 'recursive'

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'

    - name: Check and Setup Gradle Wrapper if Missing
      id: gradle-setup
      run: |
        if [ ! -f gradlew ] || [ ! -d gradle/wrapper ]; then
          echo "Gradle Wrapper missing, attempting automatic setup..."
          # Specify the Gradle version required for your project
          GRADLE_VERSION=7.0.2
          wget https://services.gradle.org/distributions/gradle-${GRADLE_VERSION}-bin.zip
          unzip -q gradle-${GRADLE_VERSION}-bin.zip
          export PATH=$PWD/gradle-${GRADLE_VERSION}/bin:$PATH
          gradle wrapper --gradle-version=${GRADLE_VERSION}
          echo "Gradle Wrapper has been set up successfully."
        else
          echo "Gradle Wrapper is present."
        fi

    - name: Grant Execution Permissions for gradlew
      run: chmod +x ./gradlew

    - name: Cache Gradle and Wrapper
      uses: actions/cache@v2
      with:
        path: |
          ~/.gradle/caches
          ~/.gradle/wrapper
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
        restore-keys: |
          ${{ runner.os }}-gradle-

    - name: Build Debug APK
      run: ./gradlew assembleDebug --stacktrace

    - name: Upload APK
      uses: actions/upload-artifact@v2
      with:
        name: app-debug-apk
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Diagnostics on Failure
      if: failure()
      run: |
        echo "Build failed. Printing diagnostics information..."
        # Add any specific diagnostics commands you might need below
        ./gradlew tasks --all || true
